// <auto-generated />
using System;
using FoodDelivery.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDelivery.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FoodDelivery.DAL.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Price = 120m,
                            Title = "Борщ"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Price = 110m,
                            Title = "Суп-лапша"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Price = 130m,
                            Title = "Курка з рисом"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Price = 150m,
                            Title = "Стейк"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Price = 140m,
                            Title = "Рибка на гарнірі"
                        },
                        new
                        {
                            Id = 6,
                            Category = 3,
                            Price = 40m,
                            Title = "Чай"
                        },
                        new
                        {
                            Id = 7,
                            Category = 3,
                            Price = 50m,
                            Title = "Лимонад"
                        },
                        new
                        {
                            Id = 8,
                            Category = 3,
                            Price = 45m,
                            Title = "Компот"
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            Price = 100m,
                            Title = "Салат Цезар"
                        },
                        new
                        {
                            Id = 10,
                            Category = 4,
                            Price = 85m,
                            Title = "Тірамісу"
                        });
                });

            modelBuilder.Entity("FoodDelivery.DAL.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            DishId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 1,
                            DishId = 3
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 1,
                            DishId = 6
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 2,
                            DishId = 2
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 2,
                            DishId = 4
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 2,
                            DishId = 7
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 3,
                            DishId = 1
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 3,
                            DishId = 5
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 3,
                            DishId = 8
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 4,
                            DishId = 2
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 4,
                            DishId = 3
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 4,
                            DishId = 6
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 4,
                            DishId = 9
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 5,
                            DishId = 1
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 5,
                            DishId = 4
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 5,
                            DishId = 7
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 6,
                            DishId = 2
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 6,
                            DishId = 5
                        },
                        new
                        {
                            Id = 19,
                            DayOfWeek = 6,
                            DishId = 8
                        },
                        new
                        {
                            Id = 20,
                            DayOfWeek = 6,
                            DishId = 10
                        },
                        new
                        {
                            Id = 21,
                            DayOfWeek = 0,
                            DishId = 1
                        },
                        new
                        {
                            Id = 22,
                            DayOfWeek = 0,
                            DishId = 3
                        },
                        new
                        {
                            Id = 23,
                            DayOfWeek = 0,
                            DishId = 6
                        });
                });

            modelBuilder.Entity("FoodDelivery.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsComplex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodDelivery.DAL.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FoodDelivery.DAL.Entities.MenuItem", b =>
                {
                    b.HasOne("FoodDelivery.DAL.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("FoodDelivery.DAL.Entities.OrderItem", b =>
                {
                    b.HasOne("FoodDelivery.DAL.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodDelivery.DAL.Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("FoodDelivery.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
